version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: pip
    directory: /tex_to_accessible_html_converter
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packaging
    schedule:
      interval: weekly
